---
# tasks file for frontend
- name: create group
  group:
    name: frontend
    state: present

- name: create service user
  user:
    name: frontend
    group: frontend
    groups: sudo, frontend
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: Downloading bash script
  get_url:
    url: https://deb.nodesource.com/setup_16.x
    dest: /home/ansible
    mode: 0777

- name: sh
  command: /home/ansible/setup_16.x

- name: "Install nodejs"
  apt:
    name: nodejs
    state: present
