---
# tasks file for frontend
- name: create group
  group:
    name: frontend
    state: present

- name: create service user
  user:
    name: frontend
    group: frontend
    groups: sudo, frontend
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: Downloading bash script
  get_url:
    url: https://deb.nodesource.com/setup_16.x
    dest: /home/ansible
    mode: 0777

- name: sh
  command: /home/ansible/setup_16.x

- name: "Install nodejs"
  apt:
    name: nodejs
    state: present

- name: copy backen unit service
  copy:
    src: /etc/systemd/system/frontend.service
    dest: /etc/systemd/system/frontend.service
    owner: frontend
    mode: '0644'

- name: create directories
  file:
    path: /var/www-data/dist/frontend
    state: directory
    owner: frontend
    group: frontend
    mode: 0775

- name: FIX DNS to resolve nexus
  become: true
  ansible.builtin.copy:
    src: /home/student/ansible2/infrastructure/ansible/files/resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: '0644'
  register: dns_fix

- name: restart systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted
  when: dns_fix.changed

- name: Downloading from nexus
  get_url:
    url: https://nexus.praktikum-services.tech/repository/std-024-12-frontend/1.0.969767/sausage-store-1.2.969767.tar.gz
    dest: /home/ansible

- name: untar 
  ansible.builtin.unarchive:
    src: /home/ansible/sausage-store.1.2.969767.tar.gz
    dest: /var/www-data/dist/frontend

- name: reread systemd unit
  systemd:
    daemon_reload: yes

- name: starting service
  service:
    name: frontend.service
    state: started 
