---
# tasks file for frontend
- name: create group
  group:
    name: "{{frontend_group}}"
    state: present

- name: create service user
  user:
    name: "{{frontend_user}}"
    group: "{{frontend_group}}"
    groups: [sudo, "{{frontend_group}}"]
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
    
- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_16.x bionic main"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: instal http-server
  shell: sudo npm install --global http-server

- name: create directories
  file:
    path: /var/www-data/dist/frontend
    state: directory
    owner: frontend
    group: "{{frontend_group}}"
    mode: 0775

- name: FIX DNS to resolve nexus
  become: true
  ansible.builtin.copy:
    src: /home/student/ansible2/infrastructure/ansible/files/resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: '0644'
  register: dns_fix

- name: restart systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted
  when: dns_fix.changed

- name: Downloading from nexus
  get_url:
    url: https://nexus.praktikum-services.tech/repository/std-024-12-frontend/1.0.969767/sausage-store-1.0.969767.tar.gz
    url_username: std-024-12
    url_password: E5h3x9Xk
    dest: /home/ansible/sausage-store.1.0.969767.tar.gz
    mode: 0777
  register: download_from_nexus

- name: Install unzip
  apt:
    name: unzip
    state: present
  when: download_from_nexus.changed

- name: untar 
  ansible.builtin.unarchive:
    remote_src: true
    src: /home/ansible/sausage-store.1.0.969767.tar.gz
    dest: /var/www-data/dist
    owner: frontend
    group: "{{frontend_group}}"
    mode: 0755

- name: copy backen unit service
  copy:
    src: /etc/systemd/system/frontend.service
    dest: /etc/systemd/system/frontend.service
    owner: frontend
    mode: '0644'

- name: reread systemd unit
  systemd:
    daemon_reload: yes

- name: starting service
  service:
    name: frontend.service
    state: started 
