---
# tasks file for frontend
- name: create group
  group:
    name: "{{frontend_group}}"
    state: present

- name: create service user
  user:
    name: "{{frontend_user}}"
    group: "{{frontend_group}}"
    groups: [sudo, "{{frontend_group}}"]
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "{{gpg_key_for_nodejs}}"
    state: present
    
- name: Install the nodejs LTS repos
  apt_repository:
    repo: "{{nodejs_repo}}"
    state: present
    update_cache: yes

- name: Install the nodejs
  apt:
    name: nodejs
    state: present

- name: instal http-server
  shell: sudo npm install --global http-server

- name: create directories
  file:
    path: "{{frontend_files_path}}"
    state: directory
    owner: "{{owner_frontend_service}}"
    group: "{{frontend_group}}"
    mode: 0775

- name: FIX DNS to resolve nexus
  become: true
  template:
    src: "resolved.j2"
    dest: "{{dest_path_to_resolvedconf_file}}/resolved.conf"
    mode: '0644'
  notify: restart systemd-resolved

- name: Downloading from nexus
  get_url:
    url: "{{nexus_url_frontend}}"
    url_username: "{{nexus_username}}"
    url_password: "{{nexus_password}}"
    dest: "{{dest_path_to_downloading_from_nexus}}"
    mode: 0777

- name: Install unzip
  apt:
    name: unzip
    state: present

- name: untar 
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{dest_path_to_downloading_from_nexus}}"
    dest: "{{path_to_untar}}"
    owner: "{{owner_frontend_service}}"
    group: "{{frontend_group}}"
    mode: 0755

- name: copy backen unit service
  copy:
    src: "{{dest_frontend_service}}/frontend.service"
    dest: "{{src_frontend_service}}/frontend.service"
    owner: "{{owner_frontend_service}}"
    mode: '0644'
  notify:
    - reread systemd unit
    - starting service

