stages: 
  - deploy


variables:
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия

deploy-kubernetes:
  stage: deploy
  only:
    changes: 
    - kubernetes/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
  image: alpine:3.18
  before_script:
    - apk add gettext
    - apk add openssh-client bash
    - apk add curl
    - apk add sudo
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - mkdir -p ~/.kube/
    - echo "$kubeconfig" >> ~/.kube/config #создаем конфиг куба из меременной гитлаба
    - curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - sudo mv ./kubectl /usr/local/bin/kubectl
    - kubectl version --client
  script:   
    - ls 
    # - mkdir -p /sausage-store2
    # - scp -r kubernetes /sausage-store2/
    - kubectl apply -f /kubernetes/backend
    - kubectl apply -f /kubernetes/backend-report
    - kubectl apply -f /kubernetes/frontend
#    - ssh ${DEV_USER}@${DEV_HOST} "rm -f ~/.kube/config" удалять не надо
  
  environment:
    name: sausage-store-url
    url: https://nikolaev-andrey-24.k8s.praktikum-services.tech # URL сосисочной в Kubernetes
