---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-{{ .Release.Name }}
spec:
  # В кластере может быть несколько Ingress Controllers, мы используем NGINX
  ingressClassName: {{  .Values.frontend.ingress.ingressClassName  }}
  tls:
  - hosts:
    - {{  .Values.frontend.ingress.host  }}
  rules:
    # Хост определяет правило направления траффика по доменному имени
  - host: {{  .Values.frontend.ingress.host  }}
    http:
      # Для различных путей в URL можно указать различные бэкенд-сервисы
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Заранее создан сервис типа ClusterIP
            # Он выступает в качестве бэкенда нашего Ingress
            name: {{  .Values.frontend.ingress.service_name  }}
            port:
              # У сервиса может быть несколько портов, указываем нужный нам
              number: {{  .Values.frontend.ingress.service_port_number  }}
