---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{  .Values.frontend.service.type  }}
  ports:
    - port: {{  .Values.frontend.service.port  }}
      protocol: {{  .Values.frontend.service.protocol  }}
      targetPort: {{  .Values.frontend.service.targetPort  }}
  selector:
    app: {{ .Chart.Name }} 
#при запуске стоит учитывать проброс порта kubectl port-forward service/frontend 8080:80 

