---
apiVersion: autoscaling/v2  #v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}-hpa
  labels:
    app: {{ .Chart.Name }}-hpa
spec:
  minReplicas: {{  .Values.backend-report.hpa.minReplicas  }}
  maxReplicas: {{  .Values.backend-report.hpa.maxReplicas  }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Chart.Name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{  .Values.backend-report.hpa.averageUtilization  }}
