---
# handlers file for backend
- name: restart systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted

- name: reread systemd unit
  systemd:
    daemon_reload: yes

- name: starting service
  service:
    name: backend.service
    state: restarted 