---
# tasks file for backend
- name: create group
  group:
    name: backend
    state: present

- name: create service user
  user:
    name: backend
    group: backend
    groups: sudo, backend
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: backend
    group: backend
    mode: 0775
  with_items:
    - /var/sausage-store/reports # рпеорты
    - /var/sausage-store/logs # дефолтные логи
    - /opt/sausage-store/bin # здесь будем хранить джарник
    - /opt/log # outputs

- name: Create File 
  file:
    path: "{{item}}"
    state: touch
    owner: backend
    group: backend
    mode: 0644
  with_items:
    - /opt/log/backend_out.log # вывод StandartOutput сервиса
    - /opt/log/sausage-store-backend.log # вывод StandartError сервиса

- name: apt-get update
  apt:
    update_cache: yes

- name: установка последней версии openjdk-16-jdk 
  apt:
    name: openjdk-16-jdk
    state: latest
    install_recommends: no

- name: Install PIP
  apt: 
    name=python3-pip 
    state=present

- name: Install lxml
  pip: 
    name=lxml

- name: Используем модуль maven_artifact, он скачает пакет приложения с Nexus
  maven_artifact:
    dest: "/opt/sausage-store/bin/sausage-store.jar"
    repository_url: "https://nexus.praktikum-services.tech/repository/sausage-store"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "1.0.976252"

- name: copy backen unit service
  copy:
    src: /etc/systemd/system/backend.service
    dest: /etc/systemd/system/backend.service
    owner: backend
    mode: '0644'
  
- name: Перечитываем конфигурацию systemd
  systemd:
    daemon_reload: yes

- name: starting service
  service:
    name: backend.service
    state: running 