---
# tasks file for backend
- name: create group
  group:
    name: backend
    state: present

- name: create service user
  user:
    name: backend
    group: backend
    groups: sudo, backend
    shell: /bin/bash
#    passowrd: "{{ item.password }}"
    state: present

- name: FIX DNS to resolve nexus
  become: true
  ansible.builtin.copy:
    src: /home/student/ansible2/infrastructure/ansible/files/resolved.conf
    dest: /etc/systemd/resolved.conf
    mode: '0644'
  register: dns_fix

- name: restart systemd-resolved
  become: true
  service:
    name: systemd-resolved
    state: restarted
  when: dns_fix.changed

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: backend
    group: backend
    mode: 0775
  with_items:
    - /var/sausage-store/reports # рпеорты
    - /var/sausage-store/logs # дефолтные логи
    - /opt/sausage-store/bin # здесь будем хранить джарник
    - /opt/log # outputs

- name: Create File 
  file:
    path: "{{item}}"
    state: touch
    owner: backend
    group: backend
    mode: 0644
  with_items:
    - /opt/log/backend_out.log # вывод StandartOutput сервиса
    - /opt/log/sausage-store-backend.log # вывод StandartError сервиса

- name: apt-get update
  apt:
    update_cache: yes

- name: instaling latest version openjdk-16-jdk 
  apt:
    name: openjdk-16-jdk
    state: latest
    install_recommends: no

- name: Install PIP
  apt: 
    name=python3-pip 
    state=present

- name: Install lxml
  pip: 
    name=lxml

- name: maven_artifact for downloading package from Nexus
  maven_artifact:
    dest: "/opt/sausage-store/bin/sausage-store.jar"
    repository_url: "https://nexus.praktikum-services.tech/repository/std-024-12-backend2"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store"
    version: "1.0.976252"

- name: copy backen unit service
  copy:
    src: /etc/systemd/system/backend.service
    dest: /etc/systemd/system/backend.service
    owner: backend
    mode: '0644'
  
- name: reread systemd unit
  systemd:
    daemon_reload: yes

- name: starting service
  service:
    name: backend.service
    state: started 
