---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{  .Values.backend.service.type  }}
  ports:
    - port: {{  .Values.backend.service.port  }}
      protocol: {{  .Values.backend.service.protocol  }}
      targetPort: {{  .Values.backend.service.targetPort  }}
  selector:
    app: {{ .Chart.Name }} 
