---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: {{  backend.VPA.updateMode}}
  resourcePolicy:
    containerPolicies:
      - containerName: {{  backend.VPA.containerName  }}
        minAllowed:
          cpu: {{  backend.VPA.minAllowed.cpu  }}
          memory: {{  backend.VPA.minAllowed.memory  }}
        maxAllowed:
          cpu: {{  backend.VPA.maxAllowed.cpu  }}
          memory: {{  backend.VPA.maxAllowed.memory  }}
        controlledResources: {{  backend.VPA.controlledResources  }}
        controlledValues: {{  backend.VPA.controlledValues  }} 
