stages: 
  - deploy

variables:
  VERSION: 1.0.${CI_PIPELINE_ID} # добавил перменную версия

deploy-kubernetes:
  stage: deploy
  only:
    changes: 
    - kubernetes/**/* #триггер для запуска пайплайна - изменения в директории kubernetes (рекурссивно)
  image: alpine:3.18
  before_script:
    - apk add gettext
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - echo "$kubeconfig" >> ~/.kube/config #создаем конфиг куба из меременной гитлаба
  script:    
    - ssh ${DEV_USER}@${DEV_HOST} "mkdir -p /home/student/sausage-store2"
    - scp -r kubernetes ${DEV_USER}@${DEV_HOST}:/home/student/sausage-store2/
    - scp -r ~/.kube/config ${DEV_USER}@${DEV_HOST}:~/.kube/config
    - ssh ${DEV_USER}@${DEV_HOST} "kubectl apply -f /home/student/sausage-store2/kubernetes/backend;
      kubectl apply -f /home/student/sausage-store2/kubernetes/backend-report;
      kubectl apply -f /home/student/sausage-store2/kubernetes/frontend;"
    - ssh ${DEV_USER}@${DEV_HOST} "rm -f ~/.kube/config" #удаляем в конце джоба

environment:
  URL: https://nikolaev-andrey-24.k8s.praktikum-services.tech # URL сосисочной в Kubernetes
